name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # Setup .npmrc file to publish to npm
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run CI
        uses: borales/actions-yarn@v4
        with:
          cmd: ci # will run `yarn ci` command
      - name: Publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
