on:
    pull_request:
      branches: [ "main", "develop" ]
name: release-please
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
